import PropTypes from 'prop-types';
import Head from 'next/head';

import Icon from 'public/vercel.svg';

// import axios from 'axios';
import withLayout from 'components/layout/Layout';

import Section from 'components/reusable/Section';
import Container from 'components/reusable/Container';
import { getData, getNavigation } from '../helpers/navigation';

const Home = () => {
  return (
    <Section>
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Icon width={100} fill={'#dddddd'} />
      </Container>
    </Section>
  );
};

export default withLayout(Home);

export const getStaticProps = async ({ locale }) => {
  const [navData, translation] = await Promise.all([
    getNavigation('pages', { locale, sort: 'navPosition' }, 5),
    getData('translation', { locale }),
  ]);

  if (!navData.length) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      navData,
      translation: translation.attributes,
    },
  };
};

Home.propTypes = {
  navData: PropTypes.arrayOf(
    PropTypes.shape({
      slug: PropTypes.string.isRequired,
      name: PropTypes.string.isRequired,
      id: PropTypes.string.isRequired,
    }),
  ).isRequired,
};
